### ISSUE TITLE
Mise à jour des données ?

### ISSUE THREAD

**Issue by bzg** [etalab/api-codes-sources-fr#9]
Hello, de nouvelles données sont disponibles sur https://github.com/etalab/data-codes-sources-fr mais n'apparaissent pas dans l'API. Peut-être le même problème que la dernière fois ?

**Comment by AntoineAugusti** [comment]
En regardant les logs, j'ai l'impression que les builds se sont croisés. Push des données au même moment ou après de la mise à jour de l'API, donc je pense qu'au prochain build, dans quelques heures, ce sera bon

**Comment by bzg** [comment]
OK, merci d'avoir regardé !

**Comment by AntoineAugusti** [comment]
Peux-tu me confirmer que c'est corrigé ?

**Comment by bzg** [comment]
Oui : https://code.etalab.gouv.fr/fr/repos?g=https%3A%2F%2Fgithub.com%2FEsupPortail

Merci !
